[project]
name = "spotifyclone"

[language]
name = "java"
version = "11"

[dependencies]
package_managers = ["maven"]

[scripts]
build = "mvn clean install"
start = "java -jar target/spotifyclone-0.0.1-SNAPSHOT.jar"
