spring.application.name=spotifyclone
# spring.datasource.url= jdbc:mysql://localhost:3306/spotifydb
# spring.datasource.username=mudavath
# spring.datasource.password=mudavath@143

spring.datasource.url = jdbc:h2:file:~/spotifyclone/src/main/spotifyclone
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true

spring.sql.init.mode= always
spring.jpa.show-sql=true
# spring.jpa.generate-ddl=true
# spring.jpa.hibernate.ddl-auto=update

# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
