spring.application.name=spotifyclone
spring.datasource.url= jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:spotifydb}
spring.datasource.username=${DB_USERNAME:mudavath}
spring.datasource.password=${DB_PASSWORD:mudavath@143}


spring.sql.init.mode= always
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
